### Assigment 1. - Models of language and NER

--- 
**Bag of Words (BOW) y Tf-idf**

By Jaime de Cecilio

#### Objective of the project

The objective of this practice is to make a notebook in Python that obtains the BOW and Tf-idf arrays of a text, and extracts the entities that are presented in a different text. The entities to extract will be of type organization, location and person.
To perform this activity, a system already trained for entity extraction will be used. It is recommended to use spaCy.

#### Activity script

**Part 1**

- In this activity you are provided with two text files, one in Spanish and one in English. They are the files hotel.csv and esp.txt.
- Read the first file, hotel.csv in a data frame and perform the necessary tasks to obtain the BOW and Tf-idf matrices.
- For these matrices, use only the **20 most frequent tokens and use the conversion of all terms to lower case**.
- Print the matrices on screen in an easily readable form. The columns must be headed by the corresponding term, and each row of the matrix will represent one of the documents contained in the CSV.

**Part 2**

- Then read the file esp.txt and obtain the entities included in this text.
- List on screen the obtained entities, entity text and corresponding category. Use the option of your choice to list the results.
- Comment on the results obtained in the entity extraction. In a professional environment, would you do anything to improve them, do you consider it necessary?

In [2]:
# librarys:

import warnings

import spacy,nltk
from spacy import displacy
import pandas as pd

warnings.filterwarnings('ignore')

stopwords = nltk.corpus.stopwords.words('spanish')
nlp_es = spacy.load('es_core_news_lg')

#### PART 1.

#### Bag of Words

In [3]:
## To begin with, let's see what the proposed file looks like: hotel.csv
## It is a CSV with two columns, one for text and the other for categories.
## As we are only interested in the text column, we read the file in a dataframe, 
## and we keep the first column in the form of a list.

reviews_hotel = pd.read_csv('/Users/jaime2/Desktop/DATA SCIENCE/5. ANALISIS DE INFORMACION NO ESTRUCTURADA/ENTREGAS/ENTREGA 1/hotel.csv')

print(reviews_hotel.head())

docs = reviews_hotel.iloc[:,0]     # we extract the first column

                                                text  label
0  Es un gran hotel; el mejor de Asunci√≥n. Buenas...      3
1  hola. no suelo criticar jamas lo que paso pero...      3
2  Escogi meses antes de mi boda una habitacion p...      3
3  Voy a se Lo mas equitativo posible; porque soy...      3
4  Esta es una experiencia de septiembre de 2016;...      3

In [4]:
# We obtain the BOW matrix from the vectorizer

from sklearn.feature_extraction.text import CountVectorizer
BOW_vectorizer = CountVectorizer(max_features=20, strip_accents="ascii", lowercase=True)
# BOW_vectorizer = CountVectorizer(max_features=20, strip_accents="ascii", lowercase=True, stop_words = stopwords)

BOW_matrix = BOW_vectorizer.fit_transform(docs)

vocab = BOW_vectorizer.get_feature_names()
pd.DataFrame(BOW_matrix.toarray(), columns=vocab)

,con,de,del,desayuno,el,en,es,excelente,hotel,la,las,lo,los,muy,no,para,personal,que,un,una
0,0,1,0,0,7,2,5,1,2,2,0,1,0,1,0,1,0,2,3,2
1,4,17,4,0,11,8,4,0,4,19,5,4,3,2,6,2,1,16,4,2
2,0,4,0,0,2,1,0,0,1,1,1,0,0,1,0,1,0,3,0,1
3,0,2,0,0,1,1,1,0,0,3,0,1,0,0,0,0,0,2,1,1
4,5,20,6,0,16,7,1,0,6,25,4,5,2,2,14,8,2,34,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,0,0,0,1,0,1,0,0,0,0,1,3,0,0,2,0,0,0
196,2,6,3,1,6,1,1,3,1,6,0,3,1,0,0,2,2,4,1,3
197,0,4,0,1,0,0,0,1,0,0,0,0,0,5,0,0,1,0,0,0
198,1,3,2,0,3,0,1,0,1,4,0,1,1,0,0,0,0,3,0,0
199,0,2,0,0,1,0,1,0,1,5,1,0,1,0,0,0,1,1,0,0

In [5]:
# And now we do the same for the matrix Tf-idf

from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf_vectorizer = TfidfVectorizer(max_features=20, strip_accents="ascii", lowercase=True)
# Tfidf_vectorizer = TfidfVectorizer(max_features=20, strip_accents="ascii", lowercase=True, stop_words = stopwords)

TF_matrix = Tfidf_vectorizer.fit_transform(docs)

vocab = Tfidf_vectorizer.get_feature_names()
pd.DataFrame(TF_matrix.toarray(), columns=vocab)

,con,de,del,desayuno,el,en,es,excelente,hotel,la,las,lo,los,muy,no,para,personal,que,un,una
0,0.000000,0.081587,0.000000,0.000000,0.588816,0.178032,0.511223,0.125505,0.190613,0.164004,0.000000,0.133947,0.000000,0.087193,0.000000,0.135770,0.000000,0.200066,0.335691,0.279143
1,0.140153,0.416795,0.146225,0.000000,0.278053,0.213999,0.122900,0.000000,0.114561,0.468200,0.195994,0.161008,0.118371,0.052404,0.262716,0.081600,0.038443,0.480968,0.134503,0.083884
2,0.000000,0.585074,0.000000,0.000000,0.301608,0.159588,0.000000,0.000000,0.170865,0.147013,0.233857,0.000000,0.000000,0.156319,0.000000,0.243409,0.000000,0.538015,0.000000,0.250223
3,0.000000,0.362548,0.000000,0.000000,0.186895,0.197781,0.227172,0.000000,0.000000,0.546589,0.000000,0.297611,0.000000,0.000000,0.000000,0.000000,0.000000,0.444517,0.248619,0.310107
4,0.108102,0.302571,0.135344,0.000000,0.249562,0.115543,0.018959,0.000000,0.106036,0.380138,0.096751,0.124188,0.048694,0.032336,0.378257,0.201406,0.047443,0.630665,0.103745,0.155283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.264004,0.184733,0.000000,0.000000,0.000000,0.201555,0.000000,0.284173,0.000000,0.000000,0.000000,0.000000,0.297299,0.592280,0.000000,0.000000,0.579323,0.000000,0.000000,0.000000
196,0.175041,0.367445,0.273938,0.094207,0.378839,0.066818,0.076747,0.282620,0.071539,0.369315,0.000000,0.301631,0.098558,0.000000,0.000000,0.203825,0.192052,0.300347,0.083992,0.314296
197,0.000000,0.556064,0.000000,0.213848,0.000000,0.000000,0.000000,0.213848,0.000000,0.000000,0.000000,0.000000,0.000000,0.742843,0.000000,0.000000,0.217978,0.000000,0.000000,0.000000
198,0.174056,0.365377,0.363195,0.000000,0.376707,0.000000,0.152630,0.000000,0.142273,0.489648,0.000000,0.199956,0.196007,0.000000,0.000000,0.000000,0.000000,0.447986,0.000000,0.000000
199,0.000000,0.307288,0.000000,0.000000,0.158408,0.000000,0.192547,0.000000,0.179481,0.772128,0.245649,0.000000,0.247267,0.000000,0.000000,0.000000,0.240914,0.188381,0.000000,0.000000

**Interpretation**.

Typical of a Bag of Words, in the rows we can find each of the elements that make up the corpus, and in the columns all the words that appear in the corpus, the fields being the number of times that word appears in each document. 

One of the traditional problems with Bag-of-Words models is that terms that occur very frequently can detract from the importance of more specific terms that occur less frequently. In fact, two problems occur in BOW:

- Each cell represents how many times a word appears in a document, regardless of how many words that document has.
- Each cell does not store information about how many documents in the total corpus contain that word. 
- The TF-IDF model attempts to solve these drawbacks by introducing a normalization factor.

#### PART 2. Entity Extraction (NER)

The objective is to identify terms with which certain entities are designated, and to classify them into:
- Persons
- Organizations 
- Places
- Dates

In [9]:
# load data

espa=open("/Users/jaime2/Desktop/DATA SCIENCE/5. ANALISIS DE INFORMACION NO ESTRUCTURADA/ENTREGAS/ENTREGA 1/esp.txt", "r", encoding="utf-8").read()
print(espa)

Cuando los cines parecen recuperar su m√∫sculo, llega a las salas de Espa√±a la pel√≠cula "Los Estados Unidos contra Billie Holiday", el desalentador retrato del director Lee Daniels sobre la persecuci√≥n del Gobierno Federal de Estados Unidos a la gran cantante de jazz desde 1947 hasta su muerte en 1959 a la edad de 44 a√±os. El t√≠tulo de la cinta toma como referencia una frase de la artista, que ingres√≥ en prisi√≥n durante un a√±o por un cargo de posesi√≥n de narc√≥ticos en el apogeo de su carrera: El caso se llama "Los Estados Unidos de Am√©rica contra Billie Holiday". Est√° basado en un cap√≠tulo del libro "Tras el grito"

In [10]:
## We run the analysis pipeline and divide into phrases
docum_analizado = nlp_es(espa)

for sent in docum_analizado.sents:
    print(sent.text)

Cuando los cines parecen recuperar su m√∫sculo, llega a las salas de Espa√±a la pel√≠cula "Los Estados Unidos contra Billie Holiday", el desalentador retrato del director Lee Daniels sobre la persecuci√≥n del Gobierno Federal de Estados Unidos a la gran cantante de jazz desde 1947 hasta su muerte en 1959 a la edad de 44 a√±os.
El t√≠tulo de la cinta toma como referencia una frase de la artista, que ingres√≥ en prisi√≥n durante un a√±o por un cargo de posesi√≥n de narc√≥ticos en el apogeo de su carrera: El caso se llama "Los Estados Unidos de Am√©rica contra Billie Holiday".
Est√° basado en un cap√≠tulo del libro "Tras el grito"

In [11]:
## Print tokens, canonical forms and recognized entities (Not requested in practice)

## POS tagging with Spacy 
spacy_pos_tagged = [(palabra.text, palabra.lemma_, palabra.pos_) for palabra in docum_analizado]
pd.DataFrame(spacy_pos_tagged, columns=['Palabra', 'F. Can√≥nica', 'POS']).T

,0,1,2,3,4,5,6,7,8,9,...,114,115,116,117,118,119,120,121,122,123
Palabra,Cuando,los,cines,parecen,recuperar,su,m√∫sculo,",",llega,a,...,un,cap√≠tulo,del,libro,"""",Tras,el,grito,"""",\n
F. Can√≥nica,Cuando,lo,cine,parecer,recuperar,su,m√∫sculo,",",llegar,a,...,uno,cap√≠tulo,del,librar,"""",Tras,el,gritar,"""",\n
POS,SCONJ,DET,NOUN,VERB,VERB,DET,NOUN,PUNCT,VERB,ADP,...,DET,NOUN,ADP,NOUN,PUNCT,ADP,DET,NOUN,PUNCT,SPACE

In [12]:
## We print entities

ents_tagged = [(ent.text, ent.label_) for ent in docum_analizado.ents]
pd.DataFrame(ents_tagged, columns=['Entidad', 'Tipo']).T

,0,1,2,3,4,5,6,7,8,9,10
Entidad,Espa√±a,Los Estados Unidos,Billie Holiday,Lee Daniels,Gobierno Federal,Estados Unidos,El t√≠tulo de la cinta,"El caso se llama ""Los Estados Unidos de Am√©rica",Billie Holiday,Est√°,Tras el grito
Tipo,LOC,LOC,MISC,PER,ORG,LOC,MISC,MISC,MISC,MISC,MISC

In [13]:
## Entities in the text

for sent in docum_analizado.sents:
    displacy.render(sent, style='ent', jupyter=True)